@SafeVault_HostAddress = https://localhost:7094

GET {{SafeVault_HostAddress}}/
Accept: text/html

###

POST {{SafeVault_HostAddress}}/submit
Content-Type: application/x-www-form-urlencoded

username=test-user&email=test%40example.com

###
